description: Configures network isolation (only on CHI@UC)

# This defines the minimum Heat version required by this template.
heat_template_version: 2015-10-15

# The resources section defines what OpenStack resources are to be deployed and
# how they should be configured.
resources:
  # 1. Network Name
  isolated_net:
    type: OS::Neutron::Net

  # 2. Subnet Name
  #   a. Subnet IP and CIDR
  #   b. DNS servers
  isolated_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: isolated_net }
      cidr: { get_param: cidr_net }
      allocation_pools: [{ "start": { get_param: dhcp_first }, "end": { get_param: dhcp_last } } ]
      dns_nameservers: [ 130.202.101.6, 130.202.101.37 ]
      ip_version: 4

  # 3. Router
  #   a. external interface (ext-net for UC)
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: ext-net }

  # 3.b. Internal router interface
  router_int:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: isolated_subnet }

  # 3.c. Static routes
  ironic_route:
    type: OS::Neutron::ExtraRoute
    properties:
      destination: 10.140.80.0/24
      nexthop: { get_param: gateway_ironic }
      router_id: { get_resource: router }

# The parameters section gathers configuration from the user.
parameters:
  cidr_net:
    type: string
    label: Private IP address range in 10.xx.yy.0/24 format
    description: 'IP range of the isolated network in 10.xx.yy.0/24 format'

  dhcp_first:
    type: string
    label: First IP address, e.g. 10.xx.yy.3
    description: 'The first IP address of the DHCP range'

  dhcp_last:
    type: string
    label: Last IP address, e.g. 10.xx.yy.254
    description: 'The last IP address of the DHCP range'

  gateway_ironic:
    type: string
    label: Gateway address for Ironic services, i.e. 10.xx.yy.2 if the first IP address is .3
    description: 'The gateway address must be one less than the first DHCP address, i.e. 10.xx.yy.2 if the first DHCP address is 10.xx.yy.3. This cannot be 10.xx.yy.1.'

# The Outputs section tells users what is available
outputs:
  dhcp_pool: 
    description: DHCP pool
    value: { get_attr: [isolated_subnet, allocation_pools] }
