# This describes what is deployed by this template.
description: Basic demonstraction of resource groups in Heat

# This defines the minimum Heat version required by this template.
heat_template_version: 2015-10-15

# The resources section defines what OpenStack resources are to be deployed and
# how they should be configured.
resources:
  # Define a login server that has a public (floating) IP attached
  login_server:
    type: OS::Nova::Server
    properties:
      flavor: baremetal
      image: CC-CentOS7
      key_name: { get_param: key_name }
      networks:
         - network: sharednet1
      scheduler_hints: { reservation: { get_param: reservation_id } }

  login_server_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  login_server_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: login_server_floating_ip }
      server_id: { get_resource: login_server }

  # Define a set of instances that can be accessed via login server
  instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          flavor: baremetal
          image: CC-CentOS7
          key_name: { get_param: key_name }
          networks:
             - network: sharednet1
          scheduler_hints: { reservation: { get_param: reservation_id } }
          user_data:
            str_replace:
              template: |
                #!/bin/bash
                # Only allow logins from login server
                sed -i 's/^#?AllowUsers .*/AllowUsers *@$login_server_ip/' /etc/ssh/sshd_config
              params:
                $login_server_ip: { get_attr: [login_server, first_address] }

# The parameters section gathers configuration from the user.
parameters:
  instance_count:
    type: number
    description: Number of server instances
    default: 1
    constraints:
      - range: { min: 1 }
        description: There must be at least one server.
  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: default
    constraints:
    - custom_constraint: nova.keypair
  reservation_id:
    type: string
    description: ID of the Blazar reservation to use for launching instances.
    constraints:
    - custom_constraint: blazar.reservation

# Output some useful information about what was created
outputs:
  login_ip:
    description: Public IP address of the login server
    value: { get_attr: [login_server_floating_ip, ip] }
  instance_ips:
    description: Private IP addresses of the server instances
    value: { get_attr: [instances, first_address] }
